---
title: "loops_and_functions"
author: "Mia Forsline"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Part 1. For loops revisted 
#### Task 1 
```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
transects <- c("Transect A", "Transect B", "Transect C")

matrix <- matrix(ncol = length(transects), nrow = length(weekdays))

for (i in seq_along(transects)) { #outer loop = columns
  for (j in seq_along(weekdays)) { #inner loop = rows 
    weekday_transect <- print(paste(weekdays[j], "-", transects[i]))
    matrix[j, i] <- weekday_transect #populate columns first 
  }
}
```

### Part 2. Functions introduced
#### Task 2
```{r}
force <- function(mass_kg, acceleration) {
  force <- mass_kg * acceleration
  print(paste("The resulting force is", force, paste0("Newtons", ".")))
}

force(mass = 3, acceleration = 3)
```

#### Task 3
```{r}
name_column <- function(df_name, col_number) {
 
  if (col_number < 1) {
    error("Column number cannot < 1")
  } else if (col_number > ncol(df_name)) {
    error(paste("Column number cannot exceed", ncol(df_name)))
    
  }
  
  colnames(df_name[col_number])
  
}

name_column(df_name = mtcars, col_number = 3)
```

### Task 4
```{r}
fish_weight <- function(fish_name, tot_length) {
  
  fish_parms <- data.frame(sci_name = c("Chanos chanos", "Sphyraena barracuda", "Caranx ignobilis"), 
                         common_name = c("Milkfish", "Great barracuda", "Giant trevally"), 
                         a_est = c(0.0905, 0.0181, 0.0353), 
                         b_est = c(2.52, 3.27, 3.05))
  
  fish_select <- dplyr::filter(fish_parms, fish_name == common_name) 
  
  weight <- fish_select$a_est * (tot_length ^ fish_select$b_est)
  
  return(weight)
}

fish_weight(fish_name = "Milkfish", tot_length = 3)

lengths <- seq(from = 0, to = 100, by = 1)

milkfish_weights <- fish_weight(fish_name = "Milkfish", tot_length = lengths)
```

### Task 5: deep ocean wave power
```{r}
wave_power_deep <- function(wave_height, period){
  p <- 0.5 * (wave_height ^ 2) * period
  return(p)
}

w_heights <- seq(from = 0, to = 3, by = 0.2)

wave_power_deep(wave_height = w_heights, period = 8)
```

### Task 6: deep and shallow wave power 
```{r}
w_power <- function(wave_depth_m, wave_height, period){
  
  if(wave_depth_m > 12){
  message("Using deep water equation")

  p <- 0.5 * (wave_height ^ 2) * period
  return(p)
  
} else if(wave_depth_m <= 12){
  
  message("Using shallow water equation")
    
  p <- 0.81 * (wave_height ^ 2) * period
  return(p)
  }
}
    

w_power(wave_depth_m = 20, wave_height = 2, period = 8)

```

